name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install libraries
        run: sudo apt-get install -y xorg-dev

      - name: Test
        run: go test -v ./...

      - name: Coverprofile
        run: make coverprofile
