- uses: actions/checkout@v4

- uses: actions/setup-go@v5
  with:
    go-version: "1.22"
- run: go test -v -coverprofile=profile.cov ./...

- uses: shogo82148/actions-goveralls@v1
  with:
    path-to-profile: profile.cov
